server:
  port: 8081

spring:
  application:
    name: lab-gift
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://115.191.48.78:3306/gift_lab?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: hmcbCpHF1QR0agihcp7Qw
    
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 30000
      connection-timeout: 10000
      max-lifetime: 1800000
      leak-detection-threshold: 5000
  data:
    redis:
      host: 115.191.48.78
      port: 6379
      password: QsCD7caC2krGtq1Kn8LB
      database: 0
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
lab: 
  gift: 
    # options: db-only, cache-preload, redis-stock
    send-mode: redis-stock
    
    cache: 
      gift: 
        maximum-size: 10000
        expire-after-write-seconds: 300
      room: 
        maximum-size: 10000
        expire-after-write-seconds: 60
    
    redis-stock: 
      key-prefix: "gift:stock:"
      reservation-key-prefix: "gift:stock:reservation:"
      reservation-ttl-seconds: 86400
      reservation-expire-seconds: 60
      init-on-startup: true
      # 生产环境不给强制覆盖
      force-init-on-startup: true
      mysql-deduct-enabled: false
    
    stock-sync: 
      enabled: true
      fixed-delay-ms: 1000
      gift-limit: 100
      batch-size: 500
      
    stock-sync-recover: 
      enabled: true
      fixed-delay-ms: 10000
      batch-size: 100
      
    stock-compensate: 
      enabled: true
      fixed-delay-ms: 5000
      timeout-seconds: 60
      batch-size: 100
    
    stock-check: 
      enabled: true
      fixed-delay-ms: 30000